a

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -14,6 +14,26 @@ commands:
             aws cloudformation delete-stack --stack-name "udapeople-frontend-${CIRCLE_WORKFLOW_ID:0:7}"
             # exit 1
 
+  revert-migrations:
+    description: Revert the last migration if successfully run in the current workflow.
+    parameters:
+      # Add parameter here     
+    steps:
+      - run:
+          name: Revert migrations
+          # Add when this will run
+          command: |
+            # Curl command here to see if there was a successful migration associated with the workflow id, store result in SUCCESS variable
+
+            SUCCESS = 1
+            if(( $SUCCESS==1 )); 
+            then
+            #  cd ~/project/backend
+            #  npm install
+            #  Add revert code here. You can find this in the Getting Started section.
+              exit 1
+            fi
+
 orbs: 
   slack: circleci/slack@4.10.1
 
@@ -243,7 +263,7 @@ jobs:
             npm run migrate > migrations_dump.txt
             # exit 1
       - run:
-          name: Send migration results to memstash
+          name: Send migration results to kdvb-backend
           command: |
             # Your code here
             if grep -q "has been executed successfully." ~/project/backend/migrations_dump.txt
@@ -304,6 +324,46 @@ jobs:
 
       - destroy_environment
         # when: on_fail
+
+  deploy-backend:
+    docker:
+      # Docker image here that supports Ansible
+      - image: python:3.10.5-alpine3.16
+    steps:
+      # Checkout code from git
+      - checkout
+      # Add ssh keys with fingerprint
+      - add_ssh_keys:
+          fingerprints: ["0d:42:f7:5c:da:67:b6:9c:d2:0e:3b:50:b2:56:7c:f1"]
+      # attach workspace
+      - attach_workspace:
+          at: .circleci/ansible
+      - run:
+          name: Install dependencies (Nodejs and NPM)
+          command: |
+            apt-get update && apt-get install -y nodejs npm
+      - run:
+          name: Install dependencies (python)
+          command: |
+            apk add --update python
+      - run:
+          name: Install dependencies (ansible)
+          command: |
+            apk add --update ansible
+      - run:
+          name: Deploy backend
+          command: |
+            # your code here
+            cd backend
+            npm i
+            npm run build
+            cd ..
+            tar -C backend -czvf artifact.tar.gz .
+            cd .circleci/ansible
+            echo "Contents of the inventory file is ..."
+            cat inventory
+            ansible-playbook -i inventory deploy-backend.yml      
+      # Here's where you will add some code to rollback on failure 
 
       # - run: apk add --update curl
       # - run:
